### ISSUE TITLE
Allow autocomplete 

### ISSUE THREAD

**Issue by kpman** [ruyadorno/ntl#12]
First, thank you for implementing this package.
I use `ntl` everyday.

Do you have any plan to support autocomplete?

https://github.com/mokkabonna/inquirer-autocomplete-prompt#readme

**Comment by ruyadorno** [comment]
hi @kpman thanks!!! 🎉 glad to see there's more people out there using **ntl** other than I 😂 

super sorry to have taken that much time for a reply but **YES** I do have plans to add autocomplete since I just recently added it to **ntl** younger brother **ipt**: https://github.com/ruyadorno/ipt/releases/tag/v1.1.0

I'm seriously considering a major revamp of **ntl** using **ipt** internally so that it would have all the goodies (improments/bugfixes) done there for free 😊

**Comment by kpman** [comment]
Hi @ruyadorno, do you have any progress for this issue?
I am really looking for it.

**Comment by ruyadorno** [comment]
hi @kpman, I'm still concentrating efforts on **ipt** v2 in which I want to reuse here, I'm sorry for the long wait but I don't have a lot of time these days (classic open source dev 😬sorry again). I rather keep my focus and once done over there, implement it the right way here 😄

in the meantime - if you're really eager to have it, I'd be open to merge a PR here that just implements `inquirer-autocomplete-prompt` the same way it's done on **ipt**: https://github.com/ruyadorno/ipt/pull/15/files if you're willing to give it a try 😉

**Comment by ruyadorno** [comment]
hi @kpman, just wanted to keep you posted, I have some good news as the rewrite of the API in **ipt** is mostly done now https://github.com/ruyadorno/ipt/pull/26

**Comment by ruyadorno** [comment]
hi @kpman heads up [v2.0.0](https://github.com/ruyadorno/ntl/releases/tag/v2.0.0) just landed with `-A` `--autocomplete` option 😄

**Comment by kpman** [comment]
Nice!!!
