### ISSUE TITLE
Feature Request: run last task

### ISSUE THREAD

**Issue by mikicho** [ruyadorno/ntl#28]
A lot of times I need to run the same task again and again (tests for example).
So I want to be able to run the last task in more convenient way for example:
```
ntl last
or
ntl rerun
```

**Comment by ruyadorno** [comment]
related to #16

**Comment by mischah** [comment]
This would be a great addition 👍 

@ruyadorno 

I would love to work on this one. Should this be just another option like:

    -r, --rerun       Rerun last selected script

**Comment by ruyadorno** [comment]
@mischah sounds good! a few questions:

- how do you plan to keep a storage/history of last run command?
- how do I change the command I want to rerun after storing it?
- what happens when the cli flag is used but there are no commands in history?
- are commands saved to this storage even when the flag is not used?

I think most of these are straightforward but it could be a good exercise to have the answers to those in your mind before starting to work in the code 😊

**Comment by mischah** [comment]
Good questions.

> * how do you plan to keep a storage/history of last run command?

I did some research about a simple key value storage like `localstorage` for node and ended up by prefering [conf](https://github.com/sindresorhus/conf) over [data-store](https://github.com/jonschlinkert/data-store) or [keyv](https://github.com/lukechilds/keyv)

> * how do I change the command I want to rerun after storing it?

Didn’t thought about that by now. But I don’t think this is actually needed. You just update it by calling `ntl` without `--rerun`. Do you think we could need something like `--reset-rerun` to clear the last command?

> * what happens when the cli flag is used but there are no commands in history?

I initially thought it’s simply ignored and `ntl` behaves like it does now. But maybe we also could additionally show a message like `Sorry, we can’t run the last command because no command is stored yet.`

> * are commands saved to this storage even when the flag is not used?

Yup. Sure thing.

**Comment by mischah** [comment]
Hej @ruyadorno 

I have two final questions that have to be answered before starting to work on this:

1. Where to store the saved last command?

    When using [conf](https://github.com/sindresorhus/conf) you can decide wether to store the data in `~/.config/ntl` or in the current working directory.

    I guess we should use the current working directory in order to make it possible to save last run tasks depending on used project instead of having a global storage of one single last command. Right?

2. Should the last command be instantaneously be executed?

    This is potentially _dangerous_ especially when having a global storage. Reason: you might have a npm script called `release` or `publish` which in worst case automatically publishes to npm. Is this something we should have in mind? Or is this only a very edgy edge case?

    This could be catched by showing the last command when running `ntl --rerun` and executing it after hitting the return key. This is of course less comfortable.

**Comment by ruyadorno** [comment]
1. 👍 to current working directory
2. yes, i know there are potential risks but imo this is the whole point of having the `rerun` as a feature (maybe having two diff flags to run with/without confirmation?)

**Comment by ruyadorno** [comment]
also, maybe it's a good idea to have a flag/option to disable the cache, e.g: `--nocache` I can see that some people would find it rather intrusive to have it saving to the local file everytime

**Comment by ruyadorno** [comment]
one more idea: it's definitely a good idea to test it with **npx** and make sure it works as intended (or maybe the intended way in this case is to not have a caching system at all?)

**Comment by goatfryed** [comment]
Hello!

In agreement with @mischah, i've implemented this feature request. As mentioned in the PR, i have trouble with the tests and therefore couldn't provide additional tests for the feature.

While working on it, the question occured how to handle cases where the last usage included the multiple option. For now i've implemented to reproduce the last usage, therefore rerunning all scripts, if multiple was given.

The --nocache option isn't implemented yet. Should nocache maybe even be the default? I think that a --save option might be better.

**Comment by ruyadorno** [comment]
ok I landed #28 into master which is now basically a `v5` branch that I'm doing a bunch of work in order to publish a new major release, for now the only breaking change I'm aware of is the fact that we're only supporting node@10+

I actually have a bunch of ideas to tweak this functionality actually, namely:
- after seeing it in action I changed my mind and I now rather store a single conf file in a `$HOME/.ntl/` dir, or maybe even a `/tmp` dir, who cares - imo the **rerun** is meant to be very ephemeral and not something anyone would care enough to have it in its sight
- add an alias (maybe `nt` ?) to also rerun the last command
- add tons of tests, my focus now is to get the library to 100% test coverage since that will make our lifes so much easier (in the process of adding more tests I'm already unveiling a few bugs, see #56 #55 we def need more of those)
- fix/test/make sure it works: rerun of multiple tasks using `-m` option

stay tuned! 

/cc @mischah

**Comment by ruyadorno** [comment]
📣 out now in [ntl@5.0.0](https://github.com/ruyadorno/ntl/releases/tag/v5.0.0) 🎉
