### ISSUE TITLE
Display task descriptions by default (but not commands)

### ISSUE THREAD

**Issue by Calinou** [ruyadorno/ntl#30]
I think it would make sense to display task descriptions by default (essentially enabling the `-d` switch by default), while hiding full commands for the sake of simplicity. The `-d` switch could be preserved to display commands for tasks that do not have a description.

This would improve discoverability of task descriptions and further encourage adding them to `package.json`.

**Comment by mischah** [comment]
Hej @Calinou,

let my recap your thoughts:

- `ntl` should behave like `ntl -d -o`
- `ntl -d` should stay the same

Am I right?

In this case `-d` should be renamed to something like:
  -f, --fallback       Displays the commands of scripts lacking a description

----

I’m not sure that this is a good idea, because it’s a rather hard braking change for users like me: I often use `ntl` for listing scripts of packages I don't own. Personal use case: Open Source contributions.

Please keep in mind that you can define an alias to keep `ntl` usage easy for you.
My personal Alias is:

    alias n="ntl -s 20"

And for my own packages where I use the description feature I always set it up like this in my `package.json`:

```json
"scripts": {
  "test": "cross-env NODE_ENV=test jest",
  "test:watch": "npm run test:coverage -- --watch",
  "tasks": "ntl -d -o"
}
```

Therefore I only have to remember, document and share the command `npm run tasks` 😗

**Comment by Calinou** [comment]
I didn't mean tasks without a description should be hidden by default (that would be a pretty bad change, usability-wise). I just meant descriptions should be displayed by default when available, while keeping the current display if no description is available.

**Comment by mischah** [comment]
Ahh. This makes sense and sounds useful 👍 

But why should we keep the `-d` in this case? 🤔

**Comment by Calinou** [comment]
> But why should we keep the `-d` in this case? :thinking:

The `-d` flag would act as a verbose mode of sorts, where the full command is displayed *only* if there is no description attached to a given task.

**Comment by eemelianov** [comment]
@ruyadorno i would like to work on this one, how should we implement the default behavior and the behavior of `-d`-flag. My proposal is:
default behavior:
- we show the script-name and the description in case one exists
- in case no description is available, we show the script-name plus full command
- in this case `-d`-flag is obsolete, but we can keep it to prevent breaking change

`-d`-flag behavior:
 - mark this flag as obsolete and to be removed

**Comment by eemelianov** [comment]
@ruyadorno ok i will implement it that way as soon as @mischah gives his approval

**Comment by mischah** [comment]
@eemelianov @ruyadorno 

>- show the script-name and the description in case one exists
>- in case no description is available, keep current behavior (only show the name)
>  - maybe we should skip `padStart` completely and only apply it on `-d` ?
>  - thinking that we could also have a mix of description/non-description scripts
>- `-d` stays similar as of-today, it enforces the `padStart` and show full commands when no description is available

Sounds legit to me 👍🏻

**Comment by ruyadorno** [comment]
awesome 👍 looks like you're good to go then @eemelianov

**Comment by ruyadorno** [comment]
hi @eemelianov, just wanted to let you know that since there was no more activity in this issue I ended up shipping the feature as I'm getting the project ready for v5, thanks for the interest and I hope you can contribute in the future 😊

**Comment by ruyadorno** [comment]
out now in [ntl@5.0.0](https://github.com/ruyadorno/ntl/releases/tag/v5.0.0) 🎉
