### ISSUE TITLE
Support a description for npm scripts

### ISSUE THREAD

**Issue by tgvashworth** [ruyadorno/ntl#4]
Hey — this project is great, exactly what I've been looking for. Thanks for building it!

My team has a lot of scripts to manage, and some have similar names but different behaviour (eg, `build` and `build_watch`). I'd like to be able to provide a description of the commands as documentation. Is that something you'd be willing to see added? (I'll happily do the PR)

I was thinking it could use the `config` key in `package.json`:

``` json
{
  "scripts": {
    "start": "...",
    "test": "...",
    "lint": "..."
  },
  "config": {
    "ntl": {
      "start": "Start a development server",
      "test": "Run the unit tests",
      "lint": "Lint JavaScript and Sass"
    }
  }
}
```

Any thoughts?

**Comment by ruyadorno** [comment]
hi @phuu really glad you like it :smile: thanks!

we had one similar contribution adding additional context to the listed tasks but it only shows the content of the npm scripts, you can see it here: #2 

Yours is a great idea and some people might find it useful, I would definitely merge it :+1: the only requirements would be to squash commits, provide tests and update the README to explain how to use it :blush:

**Comment by phuu** [comment]
@ruyadorno cool!

How do you like the idea of putting inside config.ntl? Are you likely to to use it for anything else? If so we could use a different path.

**Comment by ruyadorno** [comment]
:+1: looks awesome, please go ahead

I don't _plan_ to use it for anything else but I'm inclined to be very receptive towards accepting new ideas for this project, so we never know :blush:

**Comment by phuu** [comment]
Ok — at risk of being verbose, I'll do config.ntl.docs and see how that feels to use.

**Comment by ruyadorno** [comment]
oh, someone just did this: https://github.com/srph/npm-scripts-info

I think it's worth using something like this instead of creating/maintaining our own specs for the descriptions

**Comment by ndelangen** [comment]
Concerning intergrating this into npm itself and a description:
https://github.com/npm/npm/issues/15154#issuecomment-275791993

**Comment by zeke** [comment]
I like the bash comments idea outlined in https://github.com/npm/npm/issues/15154#issuecomment-275791993

**Comment by ruyadorno** [comment]
@zeke 👍 agreed, the bash comments looks like something that can fit well inside the scope of `ntl` without too much overhead

**Comment by mischah** [comment]
Hej @ruyadorno,

I’d love to see that feature 💖 

But I must say that I would prefer to configure descriptions via a `ntl` field in `package.json` similar to the first proposal from @tgvashworth:

```json
{
  "scripts": {
    "start": "…",
    "test": "…",
    "lint": "…"
  },
  "ntl": {
    "start": "Start a development server",
    "test": "Run the unit tests",
    "lint": "Lint JavaScript and Sass"
  }
}
```

Only difference: Get rid of the wrapping `config` property.
Reason: This is like other tools handle it (e.g. Jest, ESLint etc.)

Reason for introducing an own field instead of using bash comments:

+ Readability: Imagine [these](https://github.com/micromata/Baumeister/blob/90a84bdf144f9cf36ace962573157154d6d9a91f/package.json#L19-L46), or [these](https://github.com/medialize/ally.js/blob/b8fd3cdbb9464df08708f11cba35b7481ad846d4/package.json#L35-L83) would have additional comments 😳 
+ Maintainability: I guess having just another object would make it easier to add another useful feature: Showing only scripts which do have a description.

**Comment by mischah** [comment]
or to be more future-proof:

```json
"ntl": {
    "descriptions": {
      "start": "Start a development server",
      "test": "Run the unit tests",
      "lint": "Lint JavaScript and Sass"
    }
  }
```

This way you wouldn’t need to do a major bump in case you will store other configs into the `ntl` field.

**Comment by ruyadorno** [comment]
hi @mischah I'm totally down to support both methods! 👍 

specially after the [v2.0.0](https://github.com/ruyadorno/ntl/releases/tag/v2.0.0) refactor, there's so little code left in **ntl** itself that it can totally handle some minor bloat like that.

And then everyone can be happy! 🎉

**Comment by ruyadorno** [comment]
I'll give it a few weeks to see if anyone wants to send in a PR to support any of these description methods since I'm very burned out from all the effort that went into getting [ipt](https://github.com/ruyadorno/ipt) and **ntl** to the nice state they are now.

but fear not my friends, if nobody feels like doing it I'll implement at least one of those to start with but tbh I def want to see both description methods in!

**Comment by ndelangen** [comment]
@ruyadorno I'm sad to hear you're burned out because of the OS work. Just wanted to post, that you have no obligation to do this whatsoever, you should do things you like doing in your free time.

Truly appreciate the hard work you've put into this :bowing_man:

**Comment by mischah** [comment]
I’m about to start to work on this 😘
